version: '3.9'

services:
  db:
    image: postgres:16-alpine
    volumes:
      - ./setup_db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-}
      POSTGRES_HOST: ${POSTGRES_HOST:-db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL",
             "PGPASSWORD=${POSTGRES_PASSWORD} psql -U ${POSTGRES_USER} -h ${POSTGRES_HOST} -d ${POSTGRES_DB} \
             -c 'SELECT 1 FROM accounts LIMIT 1'"]
      interval: 30s
      timeout: 10s
      retries: 3

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.7.0
    command: [ "bash", "-c", "unset KAFKA_PORT; /etc/confluent/docker/run" ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /tmp/kafka-logs
    healthcheck:
      test: ["CMD", "nc", "-zv","kafka", "9092"]
      interval: 30s
      timeout: 10s
      retries: 3


  init-kafka:
    image: confluentinc/cp-kafka:7.7.0
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      '
      echo -e "Checking and creating Kafka topics if necessary"

      # Function to create a topic if it does not exist
      create_topic_if_not_exists() {
        local topic_name=$1
        if kafka-topics --bootstrap-server kafka:9092 --list | grep -q "^${topic_name}$"; then
          echo -e "Topic ${topic_name} already exists"
        else
          echo -e "Creating topic ${topic_name} ..."
          kafka-topics --bootstrap-server kafka:9092 --create --topic ${topic_name} --replication-factor 1 --partitions 1
        fi
      }
      # Check and create topics
      echo "Topic $TOPIC_1"  # Debug statement
      create_topic_if_not_exists $TOPIC_1
      echo "Topic $TOPIC_2"  # Debug statement
      create_topic_if_not_exists $TOPIC_2

      echo -e "Successfully checked and created topics as needed"
      '

  app:
    image: osherkoren/fastapi-app:1.44
#    build:
#      context: ./app
#      dockerfile: Dockerfile
#    volumes:
#      - ./app/src:/app/src
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-}
      POSTGRES_HOST: ${POSTGRES_HOST:-db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    healthcheck:
      test: ["CMD", "python", "-c",
             "import urllib.request; urllib.request.urlopen('http://app:80/api/v1/health').read().decode()"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker:
    image: osherkoren/kafka-worker:1.44
#    build:
#      context: ./worker
#      dockerfile: Dockerfile
#    volumes:
#        - ./worker/src:/app/src
    depends_on:
      kafka:
        condition: service_healthy
      app:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-}
      POSTGRES_HOST: ${POSTGRES_HOST:-db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}

volumes:
  postgres_data:
