apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ .Values.persistentVolumeClaim.claimName }}
  namespace: {{ .Values.namespace | default "msg-preds" }}
  labels:
    app: {{ .Values.persistentVolumeClaim.claimName }}

spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . }}
    {{- end }}

  resources:
    requests:
      storage: {{ .Values.persistence.size }}
