ingress:
#  enabled: true
  ingressClassName: nginx  # IngressClass name for ingress controller
  rules:
    - host: msg-preds.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 80
          - path: /docs
            pathType: Exact
            backend:
              service:
                name: app
                port:
                  number: 80
          - path: /api/v1/health
            pathType: Exact
            backend:
              service:
                name: app
                port:
                  number: 80
          - path: /api/v1/messages
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 80
