apiVersion: apps/v1
kind: Deployment

metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose-windows-amd64.exe -f docker-compose.yml convert
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: db
  name: db

spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\kompose\kompose-windows-amd64.exe -f docker-compose.yml convert
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/play-with-fastapi-default: "true"
        io.kompose.service: db

    spec:
      containers:
        - name: db
          image: db:16-alpine

          env:
            - name: POSTGRES_DB
              value: accounts_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: pguser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: pgpassword

          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP

          resources:
            requests:
              memory: "512Mi"   # Request half a GB of memory
              cpu: "0.5"        # Request 0.5 CPU cores
            limits:
              memory: "1Gi"     # Limit memory usage to 1 GB
              cpu: "1"          # Limit CPU usage to 1 core

          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  PGPASSWORD=${POSTGRES_PASSWORD} \
                  psql -U ${POSTGRES_USER} \
                  -h ${POSTGRES_HOST} \
                  -d ${POSTGRES_DB} \
                  -c 'SELECT 1 FROM accounts LIMIT 1'
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 10

          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: db-init
            - mountPath: /var/lib/postgresql/data
              name: db-data

      volumes:
        - name: db-init
          configMap:
            name: db-init
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data

      restartPolicy: Always
