apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: evt-user-message
  namespace: confluent
  annotations:
    kafka.topic.name: evt.userMessage
spec:
  replicas: 1
  partitionCount: 1
  kafkaClusterRef:
    name: kafka
    namespace: confluent
  configs:
    cleanup.policy: "compact"
