apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: evt-message-score
  namespace: confluent
  annotations:
    kafka.topic.name: evt.messageScore
spec:
  replicas: 1
  partitionCount: 1
  kafkaClusterRef:
    name: kafka
    namespace: confluent
  configs:
    cleanup.policy: "compact"
