apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose-windows-amd64.exe -f docker-compose.yml convert
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: worker
  name: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: worker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\kompose\kompose-windows-amd64.exe -f docker-compose.yml convert
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/play-with-fastapi-default: "true"
        io.kompose.service: worker
    spec:
      containers:
        - env:
            - name: PYTHONPATH
              value: /app
            - name: KAFKA_HOST
              value: "kafka"
            - name: KAFKA_PORT
              value: "9092"
            - name: POSTGRES_HOST
              value: db
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: accounts_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: pguser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: pgpassword
          resources:
            requests:
              memory: "512Mi"   # Request half a GB of memory
              cpu: "0.5"        # Request 0.5 CPU cores
            limits:
              memory: "1Gi"     # Limit memory usage to 1 GB
              cpu: "1"          # Limit CPU usage to 1 core

          image: osherkoren/kafka-worker:1.42
          name: worker
          ports:
            - containerPort: 81
              hostPort: 81
              protocol: TCP
      restartPolicy: Always
