repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx  # /tree/charts-chart-4.11.2

releases:
  - name: app
    namespace: msg-preds
    chart: ./app
    values:
      - ./app/values.yaml

  - name: kafka
    namespace: msg-preds
    chart: ./kafka
    values:
      - ./kafka/values.yaml

  - name: db
    namespace: msg-preds
    chart: ./db
    values:
      - ./db/values.yaml

  - name: worker
    namespace: msg-preds
    chart: ./worker
    values:
      - ./worker/values.yaml

  - name: nginx
    namespace: msg-preds
    chart: ingress-nginx/ingress-nginx
    version: 4.11.2

  - name: ingress
    namespace: msg-preds
    chart: ./ingress
    values:
      - ./ingress/values.yaml
