FROM python:3.11-slim as builder

ENV PIP_DEFAULT_TIMEOUT=100 \
    # Allow statements and log messages to immediately appear
    PYTHONUNBUFFERED=1 \
    # disable a pip version check to reduce run-time & log-spam
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    # cache is useless in docker image, so disable to reduce image size
    PIP_NO_CACHE_DIR=1

ARG POETRY_VERSION=1.7.1

WORKDIR /src

COPY app_repo/pyproject.toml .


RUN pip install "poetry==$POETRY_VERSION" \
    && poetry config virtualenvs.create false \
    && poetry install --no-root --no-cache \
    && poetry export --output requirements.txt --with test


FROM python:3.11-slim as final

WORKDIR /src

COPY --from=builder /src/requirements.txt .


RUN set -ex \
    # Security - Upgrade the package index and install security upgrades
    && apt-get update \
    && apt-get upgrade -y \
    # Install dependencies
    && pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt \
    # Clean up after upgrading - save space in the docker image
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

ENV PYTHONPATH=/src

COPY ./app_repo/app ./app
COPY ./app_repo/tests ./tests

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--log-level", "debug"]
