apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: msg-preds-apps
  namespace: argocd

spec:
  project: default

  source: # Umbrella chart for all charts manifests
    repoURL: https://github.com/OsherKoren/play_with_fastapi.git
    targetRevision: HEAD
    directories:
      - path: charts/app  # Path to the app chart
      - path: charts/db   # Path to the db chart
      - path: charts/ingress # Path to the ingress chart
      - path: charts/kafka   # Path to the kafka chart
      - path: charts/worker   # Path to the worker chart
    #path: charts  # Path to the umbrella chart directory
    #path: k8s # Path to all apps manifests

  destination:
    server: https://kubernetes.default.svc  # The default kubernetes cluster `kubectl get svc`
    namespace: msg-preds  # Check all namespaces on the cluster - `kubectl get ns`

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true  # Override manually changes on the cluster by fetching the latest version in the git repo
      prune: true  # Delete a service if deleted from the git repo
