apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: ingress-nginx
  namespace: argocd

spec:
  project: default
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.11.2
      chart: ingress-nginx

    - repoURL: https://github.com/OsherKoren/play_with_fastapi.git
      targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
