# Deploy to dev environment

name: Deploy to dev environment

on:
    pull_request:
      types: [ closed ]
      branches:
        - main

jobs:
  deploy:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
