# Deploy to dev environment

name: Deploy to dev environment

on:
  pull_request:
    branches: [ "main"]
    types:
      - closed

jobs:
  deploy:
    environment: dev
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
    - run: |
        echo The PR was merged

    - name: Checkout code
      uses: actions/checkout@v4
