# Deploy to dev server

name: Deploy main to dev

on:
  workflow_run:
    workflows: ["Register Docker images"]
    types:
      - completed

jobs:
  deploy:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate deployment package
        run: zip -r msg_preds_app.zip . -x '*.git*'

      - name: Deploy to dev server
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          region: 'eu-west-3'
          application_name: 'msg-preds'
          environment_name: 'Msg-preds-env'
          existing_bucket_name: 'elasticbeanstalk-eu-west-3-727864369235'
          version_label: "msg_preds_app-v${{ github.run_number }}"
          deployment_package: msg_preds_app.zip
          use_existing_version_if_available: true
          wait_for_environment_recovery: 60

      - name: "Successfully run CD pipeline"
        run: echo "CD part completed successfully"
