# Deploy to dev environment

name: Deploy to dev environment

on:
  workflow_run:
    workflows: ["Register Docker images"]
    types:
      - completed

jobs:
  deploy:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
