# This workflow will install Python dependencies, run tests with 3 versions of Python

name: CI

on:
#  workflow_run:
#    workflows: [ set_env, quality, test ]
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  pipeline:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Copy files
          working-directory: ${{ env.WORK_DIR }}/play_with_fastapi
          run: cp -r .github "$GITHUB_WORKSPACE/"

        - name: Run set env
          uses: ./.github/workflows/set_env.yml

        - name: Run quality
          uses: ./.github/workflows/quality.yml

        - name: Run tests
          uses: ./.github/workflows/tests.yml
