# This workflow will install Python dependencies, run tests with 3 versions of Python

name: CI

on:
#  workflow_run:
#    workflows: [ set_env, quality, test ]
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  pipeline:
      runs-on: ubuntu-latest

      steps:
#        - name: Checkout code
#          uses: actions/checkout@v4

        - name: Run set env
          uses: actions/github-script@v5
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              const { data: { workflows } } = await github.actions.listRepoWorkflows({
                owner: context.repo.owner,
                repo: context.repo.repo
              });

              const setEnvWorkflow = workflows.find(workflow => workflow.name === 'set_env');
              if (setEnvWorkflow) {
                await github.actions.createWorkflowDispatch({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  workflow_id: setEnvWorkflow.id
                });
              }
#          uses: ./.github/workflows/set_env.yml
#
#        - name: Run quality
#          uses: ./.github/workflows/quality.yml
#
#        - name: Run tests
#          uses: ./.github/workflows/tests.yml
