# This workflow will install Python dependencies, run tests with 3 versions of Python

name: CI

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  pipeline:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout set env
          uses: actions/checkout@v4

        - name: Run set env
          uses: ./.github/workflows/set_env.yml

        - name: Checkout quality
          uses: actions/checkout@v4

        - name: Run quality
          uses: ./.github/workflows/quality.yml

        - name: Checkout tests
          uses: actions/checkout@v4

        - name: Run tests
          uses: ./.github/workflows/tests.yml
