# Register Docker images in Docker Hub

name: Register Docker images

on:
  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:
  docker_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: App Docker metadata (tags, labels)
        id: app-meta
        uses: docker/metadata-action@v5
        with:
          images: osherkoren/fastapi-src

      - name: Build and push App Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: ${{ steps.app-meta.outputs.tags }}
          labels: ${{ steps.app-meta.outputs.labels }}

      - name: Processor Docker metadata (tags, labels)
        id: processor-meta
        uses: docker/metadata-action@v5
        with:
          images: osherkoren/kafka-src

      - name: Build and push Processor Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./processor
          file: ./processor/Dockerfile
          push: true
          tags: ${{ steps.processor-meta.outputs.tags }}
          labels: ${{ steps.processor-meta.outputs.labels }}
