# Register Docker images in Docker Hub

name: Register Docker images


on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed


jobs:
  register-docker:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for open pull request from 'dev' to 'main'
        id: check_pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          prs=$(gh pr list --base main --head dev --json number --jq '.[0].number')
          echo "pr_number=$prs" >> $GITHUB_ENV

      - name: Fail if no PR is found
        if: ${{ env.pr_number == '' }}
        run: |
          echo "No open pull request from 'dev' to 'main'. Exiting."
          exit 1

      - name: Set up Docker environment
        run: echo "Docker environment set up"

      - name: Determine modified folders
        id: changes
        run: |
          git fetch origin main
          if git diff --name-only origin/main | grep '^app/' > /dev/null; then
            echo "app_modified=true" >> $GITHUB_ENV
          else
            echo "app_modified=false" >> $GITHUB_ENV
          fi
          if git diff --name-only origin/main | grep '^worker/' > /dev/null; then
            echo "worker_modified=true" >> $GITHUB_ENV
          else
            echo "worker_modified=false" >> $GITHUB_ENV
          fi

      # Conditional Docker build and push for app folder
      - name: Log in to Docker Hub
        if: env.app_modified == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: App Docker metadata (tags, labels)
        id: app-meta
        if: env.app_modified == 'true'
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/fastapi-app

      - name: Build and push App Docker image
        if: env.app_modified == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: >
              ${{ secrets.DOCKER_USERNAME }}/fastapi-app:1.${{github.run_number}},
              ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
          labels: ${{ steps.app-meta.outputs.labels }}

      - name: worker Docker metadata (tags, labels)
        id: worker-meta
        if: env.worker_modified == 'true'
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/kafka-worker

      - name: Build and push worker Docker image
        if: env.worker_modified == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./worker
          file: ./worker/Dockerfile
          push: true
          tags: >
            ${{ secrets.DOCKER_USERNAME }}/kafka-worker:1.${{github.run_number}},
            ${{ secrets.DOCKER_USERNAME }}/kafka-worker:latest
          labels: ${{ steps.worker-meta.outputs.labels }}
