# Register Docker images in Docker Hub

name: Register Docker images


on:
  pull_request:
    branches: [ 'main', 'releases/**' ]
    types:
      - opened
#  workflow_run:
#    workflows: ["Tests"]
#    types:
#      - completed


jobs:
  docker_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker environment
        run: echo "Docker environment set up"

      - name: Determine modified folders
        id: changes
        run: |
          git fetch origin main
          if git diff --name-only origin/main | grep '^app/' > /dev/null; then
            echo "app_modified=true" >> $GITHUB_ENV
          else
            echo "app_modified=false" >> $GITHUB_ENV
          fi
          if git diff --name-only origin/main | grep '^worker/' > /dev/null; then
            echo "worker_modified=true" >> $GITHUB_ENV
          else
            echo "worker_modified=false" >> $GITHUB_ENV
          fi

      # Conditional Docker build and push for app folder
      - name: Log in to Docker Hub
        if: env.app_modified == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: App Docker metadata (tags, labels)
        id: app-meta
        if: env.app_modified == 'true'
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/fastapi-app

      - name: Build and push App Docker image
        if: env.app_modified == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: >
              ${{ secrets.DOCKER_USERNAME }}/fastapi-app:1.${{github.run_number}},
              ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
          labels: ${{ steps.app-meta.outputs.labels }}

      - name: worker Docker metadata (tags, labels)
        id: worker-meta
        if: env.worker_modified == 'true'
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/kafka-worker

      - name: Build and push worker Docker image
        if: env.worker_modified == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./worker
          file: ./worker/Dockerfile
          push: true
          tags: >
            ${{ secrets.DOCKER_USERNAME }}/kafka-worker:1.${{github.run_number}},
            ${{ secrets.DOCKER_USERNAME }}/kafka-worker:latest
          labels: ${{ steps.worker-meta.outputs.labels }}
