# This workflow will install Python dependencies, run tests with 3 versions of Python

name: Build and register Docker images.


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  docker_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: App Docker metadata (tags, labels)
        id: app-meta
        uses: docker/metadata-action@v5
        with:
          images: osherkoren/fastapi-app

      - name: Build and push App Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app_repo
          file: ./app_repo/Dockerfile
#          push: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.app-meta.outputs.tags }}
          labels: ${{ steps.app-meta.outputs.labels }}

      - name: Processor Docker metadata (tags, labels)
        id: processor-meta
        uses: docker/metadata-action@v5
        with:
          images: osherkoren/kafka-processor

      - name: Build and push Processor Docker image
        uses: docker/build-push-action@v5
        with:
            context: ./processor_repo
            file: ./processor_repo/Dockerfile
            push: ${{ github.event_name != 'pull_request' }}
            tags: ${{ steps.processor-meta.outputs.tags }}
            labels: ${{ steps.processor-meta.outputs.labels }}
