# Register Docker images in Docker Hub

name: Register Docker images

on:
  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:
  docker_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: App Docker metadata (tags, labels)
        id: app-meta
        uses: docker/metadata-action@v5
        with:
          images: osherkoren/fastapi-app

      - name: Build and push App Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./app/Dockerfile
          push: true
          tags: >
              ${{ secrets.DOCKER_USERNAME }}/fastapi-app:v1.${{github.run_number}},
              ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
          labels: ${{ steps.app-meta.outputs.labels }}

      - name: worker Docker metadata (tags, labels)
        id: worker-meta
        uses: docker/metadata-action@v5
        with:
          images: osherkoren/kafka-worker

      - name: Build and push worker Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./worker/Dockerfile
          push: true
          tags: >
            ${{ secrets.DOCKER_USERNAME }}/kafka-worker:v1.${{github.run_number}},
            ${{ secrets.DOCKER_USERNAME }}/kafka-worker:latest
          labels: ${{ steps.worker-meta.outputs.labels }}
