# Run tests

name: Tests

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Create .env.dev file'
        run: |
          touch .env.dev
          echo PGUSER=${{ secrets.PGUSER }} >> .env.dev
          echo PGPASSWORD=${{ secrets.PGPASSWORD }} >> .env.dev
          echo PGHOST=${{ vars.PGHOST }} >> .env.dev
          echo PGPORT=${{ vars.PGPORT }} >> .env.dev
          echo PGDATABASE=${{ vars.PGDATABASE }} >> .env.dev
          cat .env.dev

      - name: Start services with Docker Compose
        id: start_services
        run: docker-compose -f docker-compose-dev.yml --env-file ./.env.dev up -d --build

      - name: Log dev-app service output
        if: always()
        run: docker-compose -f docker-compose-dev.yml --env-file ./.env.dev logs dev-app

      - name: Log dev-processor service output
        if: always()
        run: docker-compose -f docker-compose-dev.yml --env-file ./.env.dev logs dev-processor

      - name: Wait for container to be unhealthy  # New step to wait for the container to be unhealthy
        if: always()
        run: |
          until docker ps -f "status=unhealthy" --filter "name=play_with_fastapi_dev-app" --format '{{.Status}}' | grep -q 'unhealthy'; do
            echo "Waiting for container to be unhealthy..."
            sleep 10
          done

      - name: Retrieve logs for dev-app service  # New step to retrieve logs for the dev-app service
        run: docker-compose -f docker-compose-dev.yml --env-file ./.env.dev logs dev-app

#      - name: Wait for healthchecks
#        id: wait_for_healthchecks
#        if: always()
#        run: timeout 60s sh -c 'until docker ps | grep play_with_fastapi_dev-processor_1 | grep -q healthy; do echo "Waiting for container to be healthy..."; sleep 20; done'

      - name: List Docker containers
        if: always()
        run: docker ps

      - name: Run tests
        if: steps.wait_for_healthchecks.outcome == 'success'
        run: docker-compose -f docker-compose-dev.yml exec play_with_fastapi-dev-app-1 pytest tests/

      - name: Stop services
        if: always()
        run: docker-compose -f docker-compose-dev.yml --env-file ./.env.dev down
